### PR TITLE
update gfx-hal to 0.1.0

### PR DESCRIPTION
**Pull request by karroffel**

### CODE REVIEW

**Comment by kvark** [comment]
Thank you!
bors r+

**Comment by kvark** [comment]
Do you need it published? In wgpu-rs we are currently using Rendy's memory allocation routines, although we are still on the crossroads w.r.t this aspect.

**Comment by karroffel** [comment]
I don't think I need it published. There are some things that I'd like additionally from the allocator (like persistent mapping), so I'm tempted to either extend this or write my own allocator later on.

So no need, but also wouldn't hurt if it was a 0.x release either :)

**Comment by zakarumych** [comment]
@karroffel `rendy-memory` supports persistent mapping.

**Pull request merged**
