### PR TITLE
update to gfx-hal 0.2.0

### PR DESCRIPTION
**Pull request by karroffel**
Seems like this is all that needed to be changed, my stuff still runs properly, so I assume that's all :sweat_smile:

### CODE REVIEW

**Review by kvark — APPROVED** [review]
bors r+

**Comment by zakarumych** [comment]
@karroffel Consider switching to `rendy-memory`.

**Comment by karroffel** [comment]
@omni-viral I am considering it, but it does not yet support 0.2 it seems, that's the reason I made this PR in the first place :D

**Comment by zakarumych** [comment]
@karroffel yes, but we will switch to hal 0.2 asap. Maybe even today :)

**Pull request merged**
