### PR TITLE
First implementation

### PR DESCRIPTION
**Pull request by zakarumych**
This change is [Reviewable](https://reviewable.io/reviews/omni-viral/gfx_mem/1)

### CODE REVIEW

**Comment by kvark** [comment]
I really like this. Haven't gotten through all the bits and details yet, got some notes nevertheless.
I believe a library like this would be great to have under gfx-rs org, unless you want to keep it or move to Amethyst.
Keep up the amazing work! :lgtm_strong: 

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 21 unresolved discussions.

---

*[src/arena.rs, line 54 at r1](https://reviewable.io:443/reviews/omni-viral/gfx_mem/1#-L3iYHjfOVLi3lcLaHeH:-L3iYHjgYKSYdjmxHuxG:b-xt0rcq) ([raw file](https://github.com/omni-viral/gfx_mem/blob/bb3d6fc03521d5cfa18fd05170564c2fdf62ff6a/src/arena.rs#L54)):*
> ```Rust
>         if self.is_unused() {
>             let ArenaNode { block, .. } = self;
>             owner.free(device, block);
> ```

any reason this is not `self.block`?

---

*[src/arena.rs, line 99 at r1](https://reviewable.io:443/reviews/omni-viral/gfx_mem/1#-L3iZFiqdQwnmP8-D5E9:-L3iZFirurABfx81bfnd:b-xu43eq) ([raw file](https://github.com/omni-viral/gfx_mem/blob/bb3d6fc03521d5cfa18fd05170564c2fdf62ff6a/src/arena.rs#L99)):*
> ```Rust
> 
>     fn cleanup(&mut self, owner: &mut A, device: &B::Device) {
>         while self.nodes
> ```

It would be really nice to have std's `retain` to return an iterator over excluded items. I wonder if there is an RFC on it already. cc @Gankro

---

*[src/arena.rs, line 104 at r1](https://reviewable.io:443/reviews/omni-viral/gfx_mem/1#-L3iZXsYqHX0QXRpDWQF:-L3iZXs_rHgVoS8eAVGy:brh2qw0) ([raw file](https://github.com/omni-viral/gfx_mem/blob/bb3d6fc03521d5cfa18fd05170564c2fdf62ff6a/src/arena.rs#L104)):*
> ```Rust
>             .unwrap_or(false)
>         {
>             if let Some(node) = self.nodes.pop_front() {
> ```

would probably be simpler to organize as
```rust
while let Some(node) = self.nodes.pop() {
  if node.is_used() {
    self.nodes.push(node);
    break;
  }
  // proceed as usual
}
```

---

*[src/arena.rs, line 131 at r1](https://reviewable.io:443/reviews/omni-viral/gfx_mem/1#-L3i_Tlcf4WYQxa4glO2:-L3i_Tln8IMTEdwiCw_3:b-hru0gp) ([raw file](https://github.com/omni-viral/gfx_mem/blob/bb3d6fc03521d5cfa18fd05170564c2fdf62ff6a/src/arena.rs#L131)):*
> ```Rust
>             alignment: reqs.alignment,
>         };
>         let arena_block = owner.alloc(device, info, arena_requirements)?;
> ```

I wonder, if it's idiomatic now to use `?` as much as possible?
I'd write it as `owner.alloc(..).map(AreaNode::new)`

---

*[src/arena.rs, line 157 at r1](https://reviewable.io:443/reviews/omni-viral/gfx_mem/1#-L3i_teIT1AHCT5dMhU7:-L3i_teJ2Umn6QQmRWTC:baky1ak) ([raw file](https://github.com/omni-viral/gfx_mem/blob/bb3d6fc03521d5cfa18fd05170564c2fdf62ff6a/src/arena.rs#L157)):*
> ```Rust
>         let count = self.nodes.len();
>         if let Some(ref mut hot) = self.hot.as_mut() {
>             match hot.alloc(reqs) {
> ```

any reason not to do `if let Some(block) = ...` ?

---

*[src/arena.rs, line 179 at r1](https://reviewable.io:443/reviews/omni-viral/gfx_mem/1#-L3iaHTJZ9_Q46Rb4Rpe:-L3iaHTJZ9_Q46Rb4Rpf:bf64w0s) ([raw file](https://github.com/omni-viral/gfx_mem/blob/bb3d6fc03521d5cfa18fd05170564c2fdf62ff6a/src/arena.rs#L179)):*
> ```Rust
>         let index = tag - self.freed;
> 
>         match self.nodes.len() {
> ```

hmm, this is an obscure way to use a match

---

*[src/block.rs, line 57 at r1](https://reviewable.io:443/reviews/omni-viral/gfx_mem/1#-L3iaemfBNzzPX869cOf:-L3iaemfBNzzPX869cOg:b-35pr12) ([raw file](https://github.com/omni-viral/gfx_mem/blob/bb3d6fc03521d5cfa18fd05170564c2fdf62ff6a/src/block.rs#L57)):*
> ```Rust
> {
>     /// Free this block returning it to the origin.
>     /// It must be the allocator this block was allocated from.
> ```

can we have a debug-only internal id to assert this?

---

*[src/block.rs, line 98 at r1](https://reviewable.io:443/reviews/omni-viral/gfx_mem/1#-L3ibCAkYDu5PvD3FNP0:-L3ibCAljzJbMeFaa7TQ:b-cp7nar) ([raw file](https://github.com/omni-viral/gfx_mem/blob/bb3d6fc03521d5cfa18fd05170564c2fdf62ff6a/src/block.rs#L98)):*
> ```Rust
>             tag,
>             range,
>         } = self;
> ```

why do we need to destructure `self` (here and below)?

---

*[src/chunked.rs, line 129 at r1](https://reviewable.io:443/reviews/omni-viral/gfx_mem/1#-L3ic9U0HHgY-QLoj5oR:-L3ic9U0HHgY-QLoj5oS:bgp0cop) ([raw file](https://github.com/omni-viral/gfx_mem/blob/bb3d6fc03521d5cfa18fd05170564c2fdf62ff6a/src/chunked.rs#L129)):*
> ```Rust
>     id: MemoryTypeId,
>     chunks_per_block: usize,
>     min_chunk_size: u64,
> ```

similarly, this could use a `Range`, including the getters

---

*[src/combined.rs, line 24 at r1](https://reviewable.io:443/reviews/omni-viral/gfx_mem/1#-L3icdcSLRl-4-TQX55U:-L3icdcYOvsa-91rsxHn:b-3zdiqn) ([raw file](https://github.com/omni-viral/gfx_mem/blob/bb3d6fc03521d5cfa18fd05170564c2fdf62ff6a/src/combined.rs#L24)):*
> ```Rust
> /// Allows to choose which allocator to use.
> #[derive(Debug)]
> pub struct CombinedAllocator<B>
> ```

Where is this useful, out of curiosity?

---

*[src/lib.rs, line 89 at r1](https://reviewable.io:443/reviews/omni-viral/gfx_mem/1#-L3iUP_z_QDxJec_D3Us:-L3iUPa-NfC3HqgKZQMy:b-227z69) ([raw file](https://github.com/omni-viral/gfx_mem/blob/bb3d6fc03521d5cfa18fd05170564c2fdf62ff6a/src/lib.rs#L89)):*
> ```Rust
>     /// Check if all blocks allocated from this allocator are freed.
>     /// If this function returns `true` than subsequent call to `dispose` must return `Ok(())`
>     fn is_unused(&self) -> bool;
> ```

let's have positive semantics on the queries like this, e.g. `is_used`

---

*[src/lib.rs, line 92 at r1](https://reviewable.io:443/reviews/omni-viral/gfx_mem/1#-L3iUmlHUk3rXIQoQfDo:-L3iUmlHUk3rXIQoQfDp:b-bfuegn) ([raw file](https://github.com/omni-viral/gfx_mem/blob/bb3d6fc03521d5cfa18fd05170564c2fdf62ff6a/src/lib.rs#L92)):*
> ```Rust
> 
>     /// Try to dispose of this allocator.
>     /// It will result in `Err(self)` if is in use.
> ```

neat error type :+1: 

---

*[src/lib.rs, line 101 at r1](https://reviewable.io:443/reviews/omni-viral/gfx_mem/1#-L3iVOdLdouLjoj7NxtL:-L3iVOdMp60i6PBBCInG:b-okgat7) ([raw file](https://github.com/omni-viral/gfx_mem/blob/bb3d6fc03521d5cfa18fd05170564c2fdf62ff6a/src/lib.rs#L101)):*
> ```Rust
> pub trait MemorySubAllocator<B: Backend> {
>     /// Type of allocator for this sub-allocator.
>     type Owner;
> ```

so technically the same trait as the main allocator but with `Owner = ()` or something?

---

*[src/lib.rs, line 104 at r1](https://reviewable.io:443/reviews/omni-viral/gfx_mem/1#-L3iUuN0iPsBbd_5zXnV:-L3iUuN0iPsBbd_5zXnW:b-fdotp6) ([raw file](https://github.com/omni-viral/gfx_mem/blob/bb3d6fc03521d5cfa18fd05170564c2fdf62ff6a/src/lib.rs#L104)):*
> ```Rust
> 
>     /// Information required to allocate block.
>     type Info;
> ```

let's have it cleaner as `AllocationInfo` or `Request`?

---

*[src/root.rs, line 48 at r1](https://reviewable.io:443/reviews/omni-viral/gfx_mem/1#-L3iVvw9xEX9_RwjJZbA:-L3iVvwAw4OPBAgwrrzk:b-lxkbd7) ([raw file](https://github.com/omni-viral/gfx_mem/blob/bb3d6fc03521d5cfa18fd05170564c2fdf62ff6a/src/root.rs#L48)):*
> ```Rust
>     ) -> Result<Block<B, ()>, MemoryError> {
>         let memory = device.allocate_memory(self.id, reqs.size)?;
>         let memory = Box::into_raw(Box::new(memory)); // Suboptimal
> ```

did you meant `//TODO: avoid boxing`?

---

*[src/root.rs, line 60 at r1](https://reviewable.io:443/reviews/omni-viral/gfx_mem/1#-L3iWvhD45XIEqMvC2t6:-L3iWvhEU885qc2dYtpS:b-plu6d) ([raw file](https://github.com/omni-viral/gfx_mem/blob/bb3d6fc03521d5cfa18fd05170564c2fdf62ff6a/src/root.rs#L60)):*
> ```Rust
>     }
> 
>     fn is_unused(&self) -> bool {
> ```

is there any value to the user in calling this?

---

*[src/smart.rs, line 8 at r1](https://reviewable.io:443/reviews/omni-viral/gfx_mem/1#-L3iX7jM2OIitO3zYJBX:-L3iX7jN50kAiRSnrsV3:b-o6qwgx) ([raw file](https://github.com/omni-viral/gfx_mem/blob/bb3d6fc03521d5cfa18fd05170564c2fdf62ff6a/src/smart.rs#L8)):*
> ```Rust
> 
> #[derive(Debug)]
> struct Heap {
> ```

is it really a heap? looks more like a stack to me

---

*[src/smart.rs, line 28 at r1](https://reviewable.io:443/reviews/omni-viral/gfx_mem/1#-L3iXOkU5EFQIUiVjM54:-L3iXOkVsQujJH9bppq5:btnn3f6) ([raw file](https://github.com/omni-viral/gfx_mem/blob/bb3d6fc03521d5cfa18fd05170564c2fdf62ff6a/src/smart.rs#L28)):*
> ```Rust
> 
> /// Allocator that may choose memory type based on requirements.
> /// It allocates from least used memory type from those which satisfy requirements.
> ```

Consider me sold :100: :)

---

*[src/smart.rs, line 45 at r1](https://reviewable.io:443/reviews/omni-viral/gfx_mem/1#-L3iXD_z1B4VWKkw24WO:-L3iXD_z1B4VWKkw24WP:bjee0ch) ([raw file](https://github.com/omni-viral/gfx_mem/blob/bb3d6fc03521d5cfa18fd05170564c2fdf62ff6a/src/smart.rs#L45)):*
> ```Rust
>         arena_size: u64,
>         chunks_per_block: usize,
>         min_chunk_size: u64,
> ```

nit: could be `chunk_size: Range<u64>`

---

*[src/smart.rs, line 91 at r1](https://reviewable.io:443/reviews/omni-viral/gfx_mem/1#-L3iXkFs6y3MjnetIR-n:-L3iXkFs6y3MjnetIR-o:b7ev42h) ([raw file](https://github.com/omni-viral/gfx_mem/blob/bb3d6fc03521d5cfa18fd05170564c2fdf62ff6a/src/smart.rs#L91)):*
> ```Rust
>         let allocators = self.allocators.iter_mut().enumerate();
> 
>         let mut compatible_count = 0;
> ```

nit: could just store `MemoryError` directly here

---

*[src/smart.rs, line 103 at r1](https://reviewable.io:443/reviews/omni-viral/gfx_mem/1#-L3iXil4NzoWVhGT-H0u:-L3iXil5bJz7_Cd7690D:bdq1qp7) ([raw file](https://github.com/omni-viral/gfx_mem/blob/bb3d6fc03521d5cfa18fd05170564c2fdf62ff6a/src/smart.rs#L103)):*
> ```Rust
>             })
>             .next()
>             .ok_or(MemoryError::from(if compatible_count == 0 {
> ```

why does it need a `from`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/omni-viral/gfx_mem/1#-:-L3icp84UKw8KHNP3JIF:b7a2m1m)*

**Comment by zakarumych** [comment]
Review status: all files reviewed at latest revision, 21 unresolved discussions.

---

*[src/arena.rs, line 54 at r1](https://reviewable.io:443/reviews/omni-viral/gfx_mem/1#-L3iYHjfOVLi3lcLaHeH:-L3iiCkydGsa13uAJjeY:baalrk9) ([raw file](https://github.com/omni-viral/gfx_mem/blob/bb3d6fc03521d5cfa18fd05170564c2fdf62ff6a/src/arena.rs#L54)):*
<details><summary><i>Previously, kvark (Dzmitry Malyshau) wrote…</i></summary><blockquote>

any reason this is not `self.block`?
</blockquote></details>

No reason actually.
I guess that `self.block` would look cleaner :smile: 

---

*[src/arena.rs, line 104 at r1](https://reviewable.io:443/reviews/omni-viral/gfx_mem/1#-L3iZXsYqHX0QXRpDWQF:-L3iiefwADbqFngvz6Ep:b27jd6k) ([raw file](https://github.com/omni-viral/gfx_mem/blob/bb3d6fc03521d5cfa18fd05170564c2fdf62ff6a/src/arena.rs#L104)):*
<details><summary><i>Previously, kvark (Dzmitry Malyshau) wrote…</i></summary><blockquote>

would probably be simpler to organize as
```rust
while let Some(node) = self.nodes.pop() {
  if node.is_used() {
    self.nodes.push(node);
    break;
  }
  // proceed as usual
}
```
</blockquote></details>

The problem is that you have to free nodes in order.
Otherwise it would be hard to find node from which block was allocated in `free` method.

---

*[src/arena.rs, line 131 at r1](https://reviewable.io:443/reviews/omni-viral/gfx_mem/1#-L3i_Tlcf4WYQxa4glO2:-L3ijGsbuzUvx-9ZSrXV:b-w5uzx0) ([raw file](https://github.com/omni-viral/gfx_mem/blob/bb3d6fc03521d5cfa18fd05170564c2fdf62ff6a/src/arena.rs#L131)):*
<details><summary><i>Previously, kvark (Dzmitry Malyshau) wrote…</i></summary><blockquote>

I wonder, if it's idiomatic now to use `?` as much as possible?
I'd write it as `owner.alloc(..).map(AreaNode::new)`
</blockquote></details>

Previously you could use `try!` macro to achieve same result.
I guess using `?` everywhere goes from C++ background and being used to imperative style.

---

*[src/arena.rs, line 157 at r1](https://reviewable.io:443/reviews/omni-viral/gfx_mem/1#-L3i_teIT1AHCT5dMhU7:-L3ik_PMfE-6R8GnSVpM:b6tm497) ([raw file](https://github.com/omni-viral/gfx_mem/blob/bb3d6fc03521d5cfa18fd05170564c2fdf62ff6a/src/arena.rs#L157)):*
<details><summary><i>Previously, kvark (Dzmitry Malyshau) wrote…</i></summary><blockquote>

any reason not to do `if let Some(block) = ...` ?
</blockquote></details>

No. It's refactoring artifact.

---

*[src/arena.rs, line 179 at r1](https://reviewable.io:443/reviews/omni-viral/gfx_mem/1#-L3iaHTJZ9_Q46Rb4Rpe:-L3ikg5diCC8yU2jwAq-:b-stzwpz) ([raw file](https://github.com/omni-viral/gfx_mem/blob/bb3d6fc03521d5cfa18fd05170564c2fdf62ff6a/src/arena.rs#L179)):*
<details><summary><i>Previously, kvark (Dzmitry Malyshau) wrote…</i></summary><blockquote>

hmm, this is an obscure way to use a match
</blockquote></details>

Would you prefer if-else-if-else?

---

*[src/block.rs, line 57 at r1](https://reviewable.io:443/reviews/omni-viral/gfx_mem/1#-L3iaemfBNzzPX869cOf:-L3iktJm3OFxUahqednH:bu5ttdl) ([raw file](https://github.com/omni-viral/gfx_mem/blob/bb3d6fc03521d5cfa18fd05170564c2fdf62ff6a/src/block.rs#L57)):*
<details><summary><i>Previously, kvark (Dzmitry Malyshau) wrote…</i></summary><blockquote>

can we have a debug-only internal id to assert this?
</blockquote></details>

We should. And I have an idea of how to do it.
But don't know how to check that `B::Device` is the same.

---

*[src/block.rs, line 98 at r1](https://reviewable.io:443/reviews/omni-viral/gfx_mem/1#-L3ibCAkYDu5PvD3FNP0:-L3ilI8gPs3zZYWL_FIb:b-3m139i) ([raw file](https://github.com/omni-viral/gfx_mem/blob/bb3d6fc03521d5cfa18fd05170564c2fdf62ff6a/src/block.rs#L98)):*
<details><summary><i>Previously, kvark (Dzmitry Malyshau) wrote…</i></summary><blockquote>

why do we need to destructure `self` (here and below)?
</blockquote></details>

Because returned type is different.
The other way would be constructing as
```
Block {
  relevant: self.relevant,
  memory: self.memory,
  range: self.range,
  tag: (value, self.tag),
}
```
Maybe it's better :smile: 

---

*[src/chunked.rs, line 129 at r1](https://reviewable.io:443/reviews/omni-viral/gfx_mem/1#-L3ic9U0HHgY-QLoj5oR:-L3ilqv68XyCTTFUmaSX:b-ovwawk) ([raw file](https://github.com/omni-viral/gfx_mem/blob/bb3d6fc03521d5cfa18fd05170564c2fdf62ff6a/src/chunked.rs#L129)):*
<details><summary><i>Previously, kvark (Dzmitry Malyshau) wrote…</i></summary><blockquote>

similarly, this could use a `Range`, including the getters
</blockquote></details>

Good idea!

---

*[src/combined.rs, line 24 at r1](https://reviewable.io:443/reviews/omni-viral/gfx_mem/1#-L3icdcSLRl-4-TQX55U:-L3im-ztsVKcu_8K5UR3:b-ybklg8) ([raw file](https://github.com/omni-viral/gfx_mem/blob/bb3d6fc03521d5cfa18fd05170564c2fdf62ff6a/src/combined.rs#L24)):*
<details><summary><i>Previously, kvark (Dzmitry Malyshau) wrote…</i></summary><blockquote>

Where is this useful, out of curiosity?
</blockquote></details>

To be part of custom `SmartAllocator` replacement.

---

*[src/lib.rs, line 92 at r1](https://reviewable.io:443/reviews/omni-viral/gfx_mem/1#-L3iUmlHUk3rXIQoQfDo:-L3imAllGWw_ahvlt8u5:b-o9jpm2) ([raw file](https://github.com/omni-viral/gfx_mem/blob/bb3d6fc03521d5cfa18fd05170564c2fdf62ff6a/src/lib.rs#L92)):*
<details><summary><i>Previously, kvark (Dzmitry Malyshau) wrote…</i></summary><blockquote>

neat error type :+1: 
</blockquote></details>

It's similar to [`Arc::try_unwrap`](https://doc.rust-lang.org/std/sync/struct.Arc.html#method.try_unwrap)

---

*[src/lib.rs, line 101 at r1](https://reviewable.io:443/reviews/omni-viral/gfx_mem/1#-L3iVOdLdouLjoj7NxtL:-L3imUVUPaI0MqGgHghr:b-e8sx21) ([raw file](https://github.com/omni-viral/gfx_mem/blob/bb3d6fc03521d5cfa18fd05170564c2fdf62ff6a/src/lib.rs#L101)):*
<details><summary><i>Previously, kvark (Dzmitry Malyshau) wrote…</i></summary><blockquote>

so technically the same trait as the main allocator but with `Owner = ()` or something?
</blockquote></details>

Yeap. There even was `impl<B, T> MemorySubAllocator<B> for T where T: MemoryAllocator<B> { type Owner = (); }`

---

*[src/root.rs, line 48 at r1](https://reviewable.io:443/reviews/omni-viral/gfx_mem/1#-L3iVvw9xEX9_RwjJZbA:-L3imkxkmpUrWtt1mZNF:b-tuik1l) ([raw file](https://github.com/omni-viral/gfx_mem/blob/bb3d6fc03521d5cfa18fd05170564c2fdf62ff6a/src/root.rs#L48)):*
<details><summary><i>Previously, kvark (Dzmitry Malyshau) wrote…</i></summary><blockquote>

did you meant `//TODO: avoid boxing`?
</blockquote></details>

Exactly

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/omni-viral/gfx_mem/1)*

**Comment by zakarumych** [comment]
This library is created specifically for gfx hence it makes perfect sense to put it under gfx-rs org.

---

Review status: all files reviewed at latest revision, 21 unresolved discussions.

---

*[src/root.rs, line 60 at r1](https://reviewable.io:443/reviews/omni-viral/gfx_mem/1#-L3iWvhD45XIEqMvC2t6:-L3izbWageFOKvBtsFP6:b-d8nkxc) ([raw file](https://github.com/omni-viral/gfx_mem/blob/bb3d6fc03521d5cfa18fd05170564c2fdf62ff6a/src/root.rs#L60)):*
<details><summary><i>Previously, kvark (Dzmitry Malyshau) wrote…</i></summary><blockquote>

is there any value to the user in calling this?
</blockquote></details>

It can be valuable in cases where user needs to check that call to `dispose` will result in `Ok` before trying to do so.
Although I think it would be better to have guarantees written in types instead of comments.
For instance I can change `dispose` signature so it will return `Result<Droppable<Self>, Self>`
Where `Droppable<T>` guarantees that wrapped value of type `T` can be safely dropped. And it can be unwrapped.

---

*[src/smart.rs, line 8 at r1](https://reviewable.io:443/reviews/omni-viral/gfx_mem/1#-L3iX7jM2OIitO3zYJBX:-L3j-eEdhlM_MYDFrOWw:by5qrtu) ([raw file](https://github.com/omni-viral/gfx_mem/blob/bb3d6fc03521d5cfa18fd05170564c2fdf62ff6a/src/smart.rs#L8)):*
<details><summary><i>Previously, kvark (Dzmitry Malyshau) wrote…</i></summary><blockquote>

is it really a heap? looks more like a stack to me
</blockquote></details>

Naming is inherited from gfx.

---

*[src/smart.rs, line 28 at r1](https://reviewable.io:443/reviews/omni-viral/gfx_mem/1#-L3iXOkU5EFQIUiVjM54:-L3j-oUW0dJfxgrw4SWq:bjpn40d) ([raw file](https://github.com/omni-viral/gfx_mem/blob/bb3d6fc03521d5cfa18fd05170564c2fdf62ff6a/src/smart.rs#L28)):*
<details><summary><i>Previously, kvark (Dzmitry Malyshau) wrote…</i></summary><blockquote>

Consider me sold :100: :)
</blockquote></details>

:star: 

---

*[src/smart.rs, line 45 at r1](https://reviewable.io:443/reviews/omni-viral/gfx_mem/1#-L3iXD_z1B4VWKkw24WO:-L3j-t0hqIWx5GHvafMS:b-ovwawk) ([raw file](https://github.com/omni-viral/gfx_mem/blob/bb3d6fc03521d5cfa18fd05170564c2fdf62ff6a/src/smart.rs#L45)):*
<details><summary><i>Previously, kvark (Dzmitry Malyshau) wrote…</i></summary><blockquote>

nit: could be `chunk_size: Range<u64>`
</blockquote></details>

Good idea!

---

*[src/smart.rs, line 103 at r1](https://reviewable.io:443/reviews/omni-viral/gfx_mem/1#-L3iXil4NzoWVhGT-H0u:-L3j-xpXWvuVpc8FcI34:b71ih1z) ([raw file](https://github.com/omni-viral/gfx_mem/blob/bb3d6fc03521d5cfa18fd05170564c2fdf62ff6a/src/smart.rs#L103)):*
<details><summary><i>Previously, kvark (Dzmitry Malyshau) wrote…</i></summary><blockquote>

why does it need a `from`?
</blockquote></details>

Refactoring artifact.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/omni-viral/gfx_mem/1#-:-L3izDH1G0gj4UbMc9zd:bu1mj8u)*

**Comment by kvark** [comment]
> The problem is that you have to free nodes in order.
Otherwise it would be hard to find node from which block was allocated in free method.

I don't think my proposed code changes the order.

> Would you prefer if-else-if-else?

yes

**Comment by zakarumych** [comment]
> I don't think my proposed code changes the order.

It needs not only the order to be preserved. Also you can't throw away nodes from the middle.

**Comment by kvark** [comment]
The proposed code doesn't throw away the nodes from the middle:
```rust
while let Some(node) = self.nodes.pop() {
  if node.is_used() {
    self.nodes.push(node);
    break;
  }
  // proceed as usual
}
```
I believe it's semantically equivalent to your code, but looks nicer.

**Comment by zakarumych** [comment]
This example looks nice indeed. I was thinking you suggest to use `retain`

**Pull request closed without merging**
